---
apiVersion: v1
kind: Secret
metadata:
  name: k8s-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:ibrarmunircoder/food-fiesta-k8s-manifests.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACCAQQwusfvaw5QFlPuayJvX8xaIOf4JyRlRG6W04lGNGwAAAKB71PXce9T1
    3AAAAAtzc2gtZWQyNTUxOQAAACCAQQwusfvaw5QFlPuayJvX8xaIOf4JyRlRG6W04lGNGw
    AAAEBdPseIVQjTRKzO6KLSHqwhuhmIGEJK1ojy5iQubKrqSoBBDC6x+9rDlAWU+5rIm9fz
    Fog5/gnJGVEbpbTiUY0bAAAAF2licmFybXVuaXIwMDlAZ21haWwuY29tAQIDBAUG
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"