---
apiVersion: v1
kind: Secret
metadata:
  name: k8s-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:ibrarmunircoder/food-fiesta-k8s-manifests.git
  sshPrivateKey: |
    ADD SSH KEY HERE
  insecure: "false"
  enableLfs: "true"