name: Build and test the Spring Boot Application

on:
  workflow_dispatch:
  push:
    branches: [development]


env:
  IMAGE_REPOSITORY: food-fiesta


jobs:
  build-test-push:
    name: Build, test and Push docker image to ECR repository
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::287773672913:role/food-fiesta-github-actions
          role-session-name: GithubActionsSession
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven   

      - name: Build with Maven
        run: mvn -B -DskipTests clean verify 

      - name: Package JAR
        run: mvn package -DskipTests

      - name: Release new version
        id: release
        run: |
          bash ./scripts/version-update.sh -v patch

      - name: Build docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.IMAGE_REPOSITORY  }}
          IMAGE_TAG: ${{ steps.release.outputs.new-tag }}
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG . 
      
      - name: Run the postgres container
        run: |
          docker run -d --name postgres --env POSTGRES_PASSWORD=password --env POSTGRES_DB=foodfiesta --env POSTGRES_USER=postgres --network "host" -p 5432:5432 -v postgres:/var/lib/postgresql/data postgres:alpine

      - name: Run the application
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ github.repository }}
          IMAGE_TAG: ${{ steps.release.outputs.new-tag }}
        run: |
          docker run -d --name food-fiesta --env SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/foodfiesta --env SPRING_DATASOURCE_PASSWORD=password --env SPRING_DATASOURCE_USERNAME=postgres --network "host" -p 8080:8080 $ECR_REPOSITORY:$IMAGE_TAG

      - name: Run the smoke test
        run: |
          bash ./scripts/smoke-test.sh

      - name: Build, tag, and push Docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ github.repository }}
          IMAGE_TAG: ${{ steps.release.outputs.new-tag }}
        run: |
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        